name: Jekyll CI/CD

on:
  push:
    branches:
      - develop
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Generate Gemfile
      run: |
        echo "source 'https://rubygems.org'" > Gemfile
        echo "gem 'jekyll', '~> 4.2'" >> Gemfile
        
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        
    - name: Install dependencies and build site
      run: |
        gem install bundler
        bundle install
        bundle exec jekyll build

  merge-to-main:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
    - name: Merge to main
      run: |
        git fetch origin main
        git checkout main
        git merge --no-ff "${GITHUB_REF}"
        git push origin main

  deploy:
    runs-on: ubuntu-latest
    needs: merge-to-main
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
